### ISSUE TITLE
Front-end footer

### ISSUE THREAD

**Issue by YaroslavZhabko** [brytannia/sloboda-edu-dashboard#28]
Add footer for Sloboda EDU site

**Comment by sparksofl** [comment]
@YaroslavZhabko what exactly should be in the footer?

**Comment by YaroslavZhabko** [comment]
@sparksofl for beginning, it must be strip 75px height and contain text 'Sloboda Studio © All rights reserved'

**Comment by brytannia** [comment]
let the text 'Sloboda Studio' be a link to main site
