### ISSUE TITLE
Add mode information in user account

### ISSUE THREAD

**Issue by brytannia** [brytannia/sloboda-edu-dashboard#35]
Let user to add more information about herself:
- phone
- title
- description aka "About me"
- 'in Sloboda since' : user enter date when she started works in Sloboda. Humanized date is shown in this field i.e. started work 29-03-2015 is shown as 'about a year ago'

**Comment by sparksofl** [comment]
@brytannia what kind of information should be in the title?

**Comment by brytannia** [comment]
@sparksofl like Frontend developer, or COO. Users fill in this field themselves.
