### ISSUE TITLE
Profile improvements

### ISSUE THREAD

**Issue by brytannia** [brytannia/sloboda-edu-dashboard#40]
Information isn't saved. Can't save phone number, desc, title etc. 

Other small fixes:
- group fields logically;
- work since should be datepicker;
- phone number should contain formater like this one http://www.freenetmall.com/common/jquery/FormHelpers/docs/phone.html

![screen shot 2016-02-24 at 12 15 30](https://cloud.githubusercontent.com/assets/5286652/13282316/0f18ae9e-daf1-11e5-80c9-82ffe5d8b942.png)
![screen shot 2016-02-24 at 12 16 41](https://cloud.githubusercontent.com/assets/5286652/13282320/128c0cc4-daf1-11e5-9503-3092b303431c.png)

**Comment by sparksofl** [comment]
![screenshot from 2016-02-24 12 21 27](https://cloud.githubusercontent.com/assets/11320398/13282336/32815674-daf1-11e5-9bb3-3eb70923b896.png)
@brytannia but there's datepicker

**Comment by brytannia** [comment]
@sparksofl Checked it in Chrome - works. It seems that it's some Safari problem. Right now it's a minor bug. I've added issue #41 for future development.
