### ISSUE TITLE
Add possibility to login with social network

### ISSUE THREAD

**Issue by brytannia** [brytannia/sloboda-edu-dashboard#55]
It would be nice to have a possibility to sign up and sign in with my account from some social network like Facebook, Google, Twitter of Github.
In this issue backend and frontend parts are needed both.

**Comment by arkokoley** [comment]
Hey @brytannia, 
I would like to take on this issue as a part of my Hacktoberfest challenge. What social networks are you looking forward to integrate? All four of Facebook, Google, Twitter and Github?

**Comment by brytannia** [comment]
Hi, Gaurav! Thanks for help. Actually Twitter is optional.

**Comment by arkokoley** [comment]
@brytannia I submitted PR #59 . Do review and let me know if its alright.
