### ISSUE TITLE
Add readme

### ISSUE THREAD

**Issue by brytannia** [brytannia/sloboda-edu-dashboard#57]
Remove templete and add custom readme for this project.

**Comment by Tushar-Gupta** [comment]
Hello brytannia,

I think this issue is a good place for me to start with hacktoberfest. Can you please tell me what exactly needs to be done to solve this issue? Do you want me to add a Readme.md file to the project?

**Comment by brytannia** [comment]
yeah, it should contain information how to install application and how to start to work with it.

**Comment by saltybigmac** [comment]
It would be great if the readme also included more context into this project.

**Comment by k1r8r0wn** [comment]
@sallymacnicholas Can you please provide it?

**Comment by saltybigmac** [comment]
@k1r8r0wn I would, but I don't have the context. I don't know what the goal of the site is or what it is about.

**Comment by k1r8r0wn** [comment]
@sallymacnicholas I just add the default one.

**Comment by johnfelixespinosa** [comment]
@brytannia I can take a stab at updating the readme with more context.

**Comment by ldco2016** [comment]
Has the readme file with details already added or can I jump in?

**Comment by brytannia** [comment]
Readme is added to the project. thanks for everybody for willing to help!
